title: <p align="center"> Manish Konduri </p>

title: Minimal theme
logo: /assets/img/logo.png
description: 
  <br>
  I'm working as an Associate Software Engineer in ServiceNow. I am currently taking up EPGP course in AI and ML from IIITB
  </br>


theme: jekyll-theme-minimal
